name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ros2-jazzy:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    container:
      image: ros:jazzy-ros-base
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            git \
            python3-colcon-common-extensions \
            python3-pip \
            python3-rosdep \
            python3-vcstool

      - name: Install dependencies
        shell: bash
        run: |
          set -eo pipefail
          source /opt/ros/jazzy/setup.bash
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build
        shell: bash
        run: |
          set -eo pipefail
          source /opt/ros/jazzy/setup.bash
          colcon build --symlink-install

      - name: Test
        shell: bash
        run: |
          set -eo pipefail
          source /opt/ros/jazzy/setup.bash
          source install/setup.bash
          colcon test --event-handlers console_direct+
          colcon test-result --verbose
